sigwinhq/infra

resources/YASSG/default.mk

feat: YASSG default

---

resources/PHP/common.mk
resources/PHP/php-cs-fixer.php

feat: CS fixer config

---

resources/Common/Platform/Linux/default.mk
resources/Common/default.mk
resources/Monorepo/common.mk
resources/PHP/common.mk
resources/PHP/library_monorepo.mk

Closes #58 
Closes #60 
Closes #57

fix: pass exact PHP version to Psalm

---

resources/Common/default.mk
resources/Pimcore/library.mk

feat: rename setup/pimcore to setup/test + deprecate old

---

resources/YASSG/common.mk

feat: start alias for start/dev in YASSG compat

---

resources/Pimcore/library.mk

fix: (drop and re)create database in Pimcore library

---

resources/Pimcore/library.mk

fix: clean in Pimcore library

---

resources/Pimcore/library.mk

fix: make Behat strict

---

resources/Pimcore/application.mk
resources/Pimcore/library.mk

It allows enabling jUnit per project.
Closes #49

fix: remove behat's --format pretty

---

resources/Common/default.mk
resources/Common/default/.editorconfig
resources/PHP/common.mk
resources/PHP/library.mk
resources/PHP/library/.gitattributes
resources/PHP/library/.gitignore
resources/PHP/library/.php-cs-fixer.dist.php
resources/PHP/library/Makefile
resources/PHP/library/phpstan.neon.dist
resources/PHP/library/phpunit.xml.dist
resources/PHP/library/psalm.xml.dist
resources/PHP/library_monorepo.mk
resources/Pimcore/application.mk
resources/Pimcore/common.mk
resources/Pimcore/library.mk
resources/Visual/default.mk
resources/YASSG/compat.mk
resources/YASSG/default.mk

feat: init

---

.github/workflows/build.yaml
resources/Common/Platform/Linux/default.mk
resources/Common/Platform/Windows/default.mk
resources/Common/default.mk
tests/functional/MakefileTestCase.php

Windows Powershell tests

---

.gitattributes
composer.json
resources/Lighthouse/common.mk
resources/PHP/library/.gitattributes
resources/YASSG/compat.mk
tests/functional/MakefileTestCase.php
tests/functional/YASSG/CompatTest.php

feat: Lighthouse CI

---

resources/Common/default.mk
tests/functional/MakefileTestCase.php

fix: make help always the default command

---

resources/Lighthouse/common.mk
resources/Pimcore/application.mk
tests/functional/MakefileTestCase.php
tests/functional/PHP/PhpTrait.php
tests/functional/Pimcore/ApplicationTest.php
tests/functional/YASSG/CompatTest.php

fix: setup/filesystem

---

.gitattributes
.github/workflows/release.yaml
package.json

infra: NPM setup

---

.gitattributes
.github/workflows/build.yaml
phpstan.baseline.neon
phpstan.neon.dist
phpunit.xml.dist
psalm.baseline.xml
psalm.xml.dist
resources/PHP/common.mk
resources/PHP/common/psalm.xml.dist
resources/Pimcore/application.mk
resources/Pimcore/application/phpstan.neon.dist
resources/Pimcore/application/psalm.xml.dist
resources/Pimcore/library.mk
resources/YASSG/compat/phpstan.neon.dist
resources/YASSG/compat/psalm.xml.dist
tests/functional/Common/DefaultTest.php
tests/functional/MakefileTestCase.php
tests/functional/PHP/LibraryTest.php
tests/functional/PHP/PhpTrait.php
tests/functional/Pimcore/ApplicationTest.php
tests/functional/Pimcore/LibraryTest.php
tests/functional/YASSG/CompatTest.php

bump: PHPQA 1.85

---

phpunit.xml.dist
resources/PHP/common/phpunit.xml.dist

https://twitter.com/dkarlovi/status/1608041613183356928

fix: use local PHPUnit schema

---

psalm.baseline.xml
resources/PHP/common.mk
tests/functional/MakefileTestCase.php
tests/functional/PHP/LibraryTest.php
tests/functional/PHP/PhpTrait.php
tests/functional/Pimcore/ApplicationTest.php
tests/functional/Pimcore/LibraryTest.php

fix: composer/install-highest

---

phpstan.baseline.neon
psalm.baseline.xml
tests/functional/Common/DefaultTest.php
tests/functional/MakefileTestCase.php
tests/functional/PHP/LibraryTest.php
tests/functional/PHP/PhpTrait.php
tests/functional/Pimcore/ApplicationTest.php
tests/functional/Pimcore/LibraryTest.php
tests/functional/YASSG/CompatTest.php

tests: test PHP_VERSION for PHPQA usage

---

resources/PHP/common.mk
tests/functional/PHP/PhpTrait.php

feat: more precise Infection, only covering test cases

---

phpstan.baseline.neon
psalm.baseline.xml
resources/PHP/phar.mk
resources/PHP/phar/box.json.dist
tests/functional/MakefileTestCase.php
tests/functional/PHP/PharTest.php
tests/functional/PHP/PhpTrait.php

feat: PHAR

---

resources/Pimcore/application.mk
tests/functional/PHP/PhpTrait.php

fix: remove --ignore-existing-config in Pimcore, obsoleted in 11

---

resources/PHP/common/infection.json.dist

fix: add default Infection config

---

resources/PHP/common.mk
tests/functional/PHP/PhpTrait.php

feat: allow passing DOCKER_ENV vars
